Files campareble
anastasia-mishchenko/hillel pull request #7
Opened 2021-08-05 22:40 UTC by anastasia-mishchenko

2021-08-05 22:42 UTC, anastasia-mishchenko commented on src/main/java/filesComparable/files/Main.java
> +            Files.createFile(Path.of("src/" + fileName + ".txt"));
на этом этапе у меня идея ругаеться и не хочет создавать файл. Подскажите как создать и вообще в правильном ли напрвлении я двигаюсь

2021-08-06 08:45 UTC, AnnaKlueva requested changes

2021-08-06 08:45 UTC, AnnaKlueva commented on src/main/java/filesComparable/files/Main.java
> +            Files.createFile(Path.of("src/" + fileName + ".txt"));
Да, в правильном направлении двигаетесь 
Ругается потому что Path.of() работает для Java9
Есть два варианта - использовать версию джавы. 9 или выше
Или взять пример из занятия

2021-08-16 12:35 UTC, AnnaKlueva approved these changes

2021-08-16 12:35 UTC, merged